### ISSUE TITLE
Why need 3 .gitignore files?

### ISSUE THREAD

**Issue by rstm-sf** [ahopper/Avalonia.IconPacks#1]
Hello!

Why need 3 .gitignore files?

It seems to me that one root file is enough.

PS.: We can to try migrate to new project sdk with help [CsprojToVs2017](https://github.com/hvanbakel/CsprojToVs2017) for `MetroIconPackExport`?

**Comment by ahopper** [comment]
I'm sure your right about the .gitignore, I added MetroIconPackExport in a hurry and messed it up.  The MahApps.Metro.IconPacks project has an Avalonia version in the pipeline, once that exists I hope I can simply remove the wpf MetroIconPackExport and do everything in the Avalonia project, I'm tempted to wait for that unless the old style project is causing a problem.

**Comment by rstm-sf** [comment]
Ok. Thanks for the answer!
