### ISSUE TITLE
VS2019 Image Library

### ISSUE THREAD

**Issue by swdriessen** [ahopper/Avalonia.IconPacks#2]
Hey, do you have plans to include the VS2019 Image Library?

[Link](https://www.microsoft.com/en-us/download/details.aspx?id=35825)

**Comment by ahopper** [comment]
Just had a quick look at it and hopefully the same .tt importer used on the previous ones will work, I'll have a go. Thanks for the link.

**Comment by ahopper** [comment]
They are now imported , there are a few that need some more work on the import script, they are listed at the end of the xaml file

**Comment by swdriessen** [comment]
Cool, thanks!
